---
driver:
  name: vagrant
  customize:
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: oracle-12c
    run_list:
      - recipe[oracle::default]
    attributes:
      oracle:
        rdbms:
          dbbin_version: '12c'
          install_files: ['http://192.168.1.222:8000/linuxamd64_12102_database_1of2.zip', 'http://192.168.1.222:8000/linuxamd64_12102_database_2of2.zip']
          latest_patch:
            is_installed: true
        user:
          pw_set: true
  - name: oracle-11g
    run_list:
      - recipe[oracle::default]
    attributes:
      oracle:
        rdbms:
          dbbin_version: '11g'
          install_files: ['http://192.168.1.222:8000/linux.x64_11gR2_database_1of2.zip', 'http://192.168.1.222:8000/linux.x64_11gR2_database_2of2.zip']
          latest_patch:
            is_installed: true
        user:
          pw_set: true
